#!/usr/bin/env bash

# Load global styles, colors and icons
source "${CONFIG_DIR}/configs/ui-defaults.sh"

sketchybar --bar "${bar[@]}" --default "${item_defaults[@]}"

#source "${CONFIG_DIR}/items/aerospace_item.sh"

# Right side
source "${CONFIG_DIR}/items/datetime.sh"

##### Force all scripts to run the first time (never do this in a script) #####
#sketchybar --hotload on
sketchybar --update
